name: Deploy Vite App to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Copy built files to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # Agar parol o'rniga SSH kalit ishlatilsa:
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/"
          target: "/var/www/complex-solutions/dist"
          strip_components: 1  # Bu qo'shimcha: Keraksiz papkalarni olib tashlash uchun ishlatiladi

      - name: Set permissions & reload Nginx via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # Yoki:
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            # Fayllarga va papkalarga to'g'ri ruxsatlar berish
            sudo chown -R www-data:www-data /var/www/complex-solutions/dist
            sudo chmod -R 755 /var/www/complex-solutions/dist

            # Nginxni qayta yuklash
            sudo systemctl reload nginx

            # Nginx holatini tekshirish
            sudo systemctl status nginx
